menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单||fas fa-list:
    音乐: /music/ || fas fa-music
    技能考试: /static/operations/ || iconfont icon-shoushudao1
    放射防护考试: /static/radiations/ || iconfont icon-radiation
    小鼠模型: /static/model/ || iconfont icon-jiandanmoxing
    课表: /static/timetable || iconfont icon--timetable
    员工卡: /static/workingcard || iconfont icon-bangdingyuangongka
    雷达图: /static/radar || iconfont icon-radarchart
    电测听: /static/audiogram || iconfont icon-hearing
    图像重建: /static/medreconstruct || iconfont icon-115
  关于我: /static/cv || fas fa-heart

copy:
  enable: true
  copyright:
    enable: false
    limit_count: 50

index_img: /images/anatomy.jpg
favicon: /images/favicon.png

# If the banner of page not setting, it will show the top_img
default_top_img: /images/chess.jpg

# The banner image of archive page
archive_img: /images/time.jpg
tag_per_img:
category_per_img:

avatar:
  img: /images/avatar.jpg
  effect: false

footer:
  owner:
    enable: true
    since: 2023
  custom_text: 很高兴遇见你。
  copyright: false # Copyright of theme and framework

cover:
  # display the cover or not (是否顯示文章封面)
  index_enable: true
  aside_enable: true
  archives_enable: true
  # the position of cover in home page (封面顯示的位置)
  # left/right/both
  position: both
  # When cover is not set, the default cover is displayed (當沒有設置cover時，默認的封面顯示)
  default_cover:
    - /images/ChristmasTrees.png
    - /images/CMYK.png
    - /images/dopamine.png
    - /images/tardis.png
    - /images/ink.png
    - /images/memory.png
    - /images/mountain.png
    - /images/piano.jpg
    - /images/rocket.png

local_search:
  enable: true
  preload: false
  CDN:

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: Tech nerd, Amateur programmar, Medical Student
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/tctco
  card_announcement:
    enable: false
    content: This is my Blog
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works

social:
  fab fa-qq: tencent://AddContact/?fromId=45&fromSubId=1&subcmd=all&uin=859267560&website=www.oicqzone.com
  fab fa-github: https://github.com/tctco || Github
  fas fa-envelope: mailto:tctco2018@gmail.com || Email

sharejs:
  enable: true
  sites: wechat,weibo,qq,facebook,twitter

canvas_fluttering_ribbon:
  enable: true
  mobile: false

runtimeshow:
  enable: true
  publish_date: 2/2/2023 00:00:00

aplayerInject:
  enable: true
  per_page: true

inject:
  head:
    - <link rel="stylesheet" href="//at.alicdn.com/t/c/font_3878240_kz3gpk6zi4c.css">
    - <link rel="stylesheet" href="/static/css/bilibili.css">
  bottom:

katex:
  enable: true
  per_page: true
  hide_scrollbar: true

preloader:
  enable: true
